version: '3'

services:

  spa:
    build:
      context: ./spa/
      dockerfile: Dockerfile
    container_name: spa
    command: "node_modules/.bin/webpack-dev-server"
    environment:
      NODE_ENV: development
    volumes:
      - ./spa:/SPA
      - /SPA/node_modules
    expose:
      - 8000

  nginx:
    build:
      context: ./nginx/
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - "8000:8000"
    depends_on:
      - spa
    links:
      - spa
